export enum IconType {
  location = "location",
  mail = "mail",
  phoneCall = "phoneCall",
  callUs = "callUs",
  plantSmall = "plantSmall",
  branchCutting = "branchCutting",
  flowerScaping = "flowerScaping",
  gardenDesign = "gardenDesign",
  grassCutting = "grassCutting",
  irrigation = "irrigation",
  plantGrowing = "plantGrowing",
  treePlanting = "treePlanting",
  weedsControl = "weedsControl",
  clientsTrust = "clientsTrust",
  ourMission = "ourMission",
  ourVision = "ourVision",
  supportTeam = "supportTeam",
}
